### ISSUE TITLE
Test failures related to RETURNN updates

### ISSUE THREAD

**Issue by vieting** [rwth-i6/pytorch-to-returnn#50]
Some tests (e.g. `test_converter.test_naming_inner_func_functional_with_buffer` and `test_layers.test_dummy_input_shape`) fail with the most recent version of RETURNN. See the checks on my fork here: https://github.com/vieting/pytorch-to-returnn/commit/1578ed50193d111e39f1f1018f90cda6ee827019

This seems to be introduced with https://github.com/rwth-i6/returnn/commit/6283b2d367c68f029bef221e5edf12d4abeb95b8. Could you please have a quick look at this @albertz?

**Comment by albertz** [comment]
(Ref: [Test](https://github.com/vieting/pytorch-to-returnn/runs/3359763791), [test](https://github.com/vieting/pytorch-to-returnn/runs/3359763823).)

The failing code uses `session.run(...size_placeholder, ...)`.

This doesn't work anymore because `size_placeholder` is not a simple dict anymore. However, you can convert it to one, by just adding `.as_dict()`, i.e. like `size_placeholder.as_dict()`. See also the commit you referenced.

That should fix the problem.

**Comment by vieting** [comment]
Thanks! I created a corresponding PR (#51).
